//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chess.Domain.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nama.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zovem se Jan Bjeličić i ovo je moj diplomski rad za modul programsko inženjerstvo i informacijski sustavi na fakultetu elektrotehnike i
        ///        računarstva u Zagrebu. Dolazim iz malog grada po imenu Križevci u sjeverozapadnoj Hrvatskoj gdje sam završio osnovnu i srednju školu. Ljubav
        ///        za programiranjem započela je kada sam se upisao na fakultet i nedugo nakon toga sam krenuo razvijati mobilne i web aplikacija te rješavati
        ///        algoritamske probleme. Razlog zašto sam počeo raditi šahovsku strani [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj partije.
        /// </summary>
        public static string AddMatches {
            get {
                return ResourceManager.GetString("AddMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj probleme.
        /// </summary>
        public static string AddProblems {
            get {
                return ResourceManager.GetString("AddProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igranje na komplikacije je ekstremna mjera na koju igrač treba igrati samo ako ne može pronaći razumni i logički plan..
        /// </summary>
        public static string AlekhineCites {
            get {
                return ResourceManager.GetString("AlekhineCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednom prilikom je Aljehin trebao održati simultanku na 40 ploča. U međuvremenu
        ///            je utjecajni političar izrazio želju da želi igrati i dodana je 41. ploča. Dok je Aljehin došao do te ploče samo ju je preokrenuo..
        /// </summary>
        public static string AlekhineDescription {
            get {
                return ResourceManager.GetString("AlekhineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amater.
        /// </summary>
        public static string Amateur {
            get {
                return ResourceManager.GetString("Amateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zovu ga &quot;Tiger of Madras&quot;..
        /// </summary>
        public static string AnandDescription {
            get {
                return ResourceManager.GetString("AnandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chess Masters.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni da želite obrisati {0}?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteThis {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povratak na listu.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početnik.
        /// </summary>
        public static string Beginner {
            get {
                return ResourceManager.GetString("Beginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najbolji igrači.
        /// </summary>
        public static string BestPlayers {
            get {
                return ResourceManager.GetString("BestPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najbolji problemisti.
        /// </summary>
        public static string BestProblemSolvers {
            get {
                return ResourceManager.GetString("BestProblemSolvers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crni.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crni je prvi na potezu.
        /// </summary>
        public static string BlackIsPlayingFirst {
            get {
                return ResourceManager.GetString("BlackIsPlayingFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igrao sam blic partiju jednom. Bilo je to u vlaku 1929..
        /// </summary>
        public static string BotvinnikCites {
            get {
                return ResourceManager.GetString("BotvinnikCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedini svjetski prvak koji je igrao protiv 12 svjetskih prvaka! Sa svima od Laskera do Kramnika..
        /// </summary>
        public static string BotvinnikDescription {
            get {
                return ResourceManager.GetString("BotvinnikDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandidat.
        /// </summary>
        public static string Candidate {
            get {
                return ResourceManager.GetString("Candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobar igrač uvijek ima sreće..
        /// </summary>
        public static string CapablancaCites {
            get {
                return ResourceManager.GetString("CapablancaCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jose Raul Capablanca tijekom igranja turnira u razdoblju od 1916 do 1924 godine
        ///            nije izgubio nijednu partiju. Osim što su ga poznavali kao velikog šahovskog majstora, Capablanca je bio poznat kao i veliki ljubitelj žena..
        /// </summary>
        public static string CapablancaDescription {
            get {
                return ResourceManager.GetString("CapablancaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matirao je Bill Gatesa u 9 poteza..
        /// </summary>
        public static string CarlsenDescription {
            get {
                return ResourceManager.GetString("CarlsenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izazov.
        /// </summary>
        public static string Challenge {
            get {
                return ResourceManager.GetString("Challenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjeni lozinku.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šahovska akademija.
        /// </summary>
        public static string ChessAcademy {
            get {
                return ResourceManager.GetString("ChessAcademy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citati.
        /// </summary>
        public static string Cites {
            get {
                return ResourceManager.GetString("Cites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čisto.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentiraj.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentari.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi novu lozinku.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi lozinku.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unijeli ste ispravan potez..
        /// </summary>
        public static string CorrectMoveMessage {
            get {
                return ResourceManager.GetString("CorrectMoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesi.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravite novi račun .
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesi novu igru.
        /// </summary>
        public static string CreateNewGame {
            get {
                return ResourceManager.GetString("CreateNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesi novu partiju.
        /// </summary>
        public static string CreateNewMatch {
            get {
                return ResourceManager.GetString("CreateNewMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesi novi problem.
        /// </summary>
        public static string CreateNewProblem {
            get {
                return ResourceManager.GetString("CreateNewProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski.
        /// </summary>
        public static string Croatian {
            get {
                return ResourceManager.GetString("Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna lozinka.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do pogreške. Molimo vas provjerite unesene podatke i pokušajte ponovno. Ukoliko još uvijek dolazi do problema javite nam se..
        /// </summary>
        public static string DefaultErrorMessage {
            get {
                return ResourceManager.GetString("DefaultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisanje.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Težina.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remi.
        /// </summary>
        public static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime za ovaj email već postoji. Molim vas unesite drugi email..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime već postoji. Unesite drugo ime..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi igru.
        /// </summary>
        public static string EditGame {
            get {
                return ResourceManager.GetString("EditGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi partiju.
        /// </summary>
        public static string EditMatch {
            get {
                return ResourceManager.GetString("EditMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi problem.
        /// </summary>
        public static string EditProblem {
            get {
                return ResourceManager.GetString("EditProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najbolji način kako se može doći do mene je preko mog gmail računa:.
        /// </summary>
        public static string EmailContactDescription {
            get {
                return ResourceManager.GetString("EmailContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravna email adresa.
        /// </summary>
        public static string EmailErrorMessage {
            get {
                return ResourceManager.GetString("EmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konačnice.
        /// </summary>
        public static string Endings {
            get {
                return ResourceManager.GetString("Endings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategija zahtijeva razmišljanje, taktika zahtijeva opažanje..
        /// </summary>
        public static string EuweCites {
            get {
                return ResourceManager.GetString("EuweCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Euwe je svoj život više posvećivao matematici nego šahu..
        /// </summary>
        public static string EuweDescription {
            get {
                return ResourceManager.GetString("EuweDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanjski login.
        /// </summary>
        public static string ExternalLogins {
            get {
                return ResourceManager.GetString("ExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznate partije.
        /// </summary>
        public static string FamousGames {
            get {
                return ResourceManager.GetString("FamousGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtriraj.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga po imenu.
        /// </summary>
        public static string FindByName {
            get {
                return ResourceManager.GetString("FindByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prvi princip napada jest : &quot;Ne daj protivniku da se razvije!&quot;.
        /// </summary>
        public static string FineCites {
            get {
                return ResourceManager.GetString("FineCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šah je rat na ploči gdje je cilj srušiti protivnikov um.&lt;br/&gt;Koncetriraj se na materijalne dobitke. Sve što ti protivnik daje, uzmi, osim ako ne vidiš dobar razlog za suprotno..
        /// </summary>
        public static string FischerCites {
            get {
                return ResourceManager.GetString("FischerCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fischer je izgubio samo 3 partije u 8 prvenstava SAD-a koja je osvojio. Nakon što su odbili njegove uvjete za odigravanje meča sa Karpovom odlučeno je da je Fischer predao bez borbe svoju titulu svjetskog prvaka 1975..
        /// </summary>
        public static string FischerDescription {
            get {
                return ResourceManager.GetString("FischerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatak.
        /// </summary>
        public static string Gain {
            get {
                return ResourceManager.GetString("Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijednost dodatka mora biti između 0 i 30..
        /// </summary>
        public static string GainRangeErrorMessage {
            get {
                return ResourceManager.GetString("GainRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti dodatak..
        /// </summary>
        public static string GainRequiredErrorMessage {
            get {
                return ResourceManager.GetString("GainRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igra.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igre.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dohvati rješenje.
        /// </summary>
        public static string GetSolution {
            get {
                return ResourceManager.GetString("GetSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje ostale projekte možete vidjeti na.
        /// </summary>
        public static string GitHubContactDescription {
            get {
                return ResourceManager.GetString("GitHubContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velemajstor.
        /// </summary>
        public static string GrandMaster {
            get {
                return ResourceManager.GetString("GrandMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povijest.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslovnica.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odigrali ste neispravan potez, molimo pokušajte ponovno..
        /// </summary>
        public static string IncorrectMoveMessage {
            get {
                return ResourceManager.GetString("IncorrectMoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najbolja stranica za testiranje šahovskih vještina. Također način za treniranje moždanih vijuga. Dostupne edukacijske poveznice.
        /// </summary>
        public static string IndexText {
            get {
                return ResourceManager.GetString("IndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresa je neispravna. Molim vas unesite ispravni email..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je neispravna. Molim vas unesite ispravnu lozinku..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za rejting.
        /// </summary>
        public static string IsRated {
            get {
                return ResourceManager.GetString("IsRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rješen?.
        /// </summary>
        public static string IsSolved {
            get {
                return ResourceManager.GetString("IsSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karpov je bio poznat i kao veliki kolekcionar poštanskih maraka..
        /// </summary>
        public static string KarpovDescription {
            get {
                return ResourceManager.GetString("KarpovDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U šahu su pravila fiksna i rezultat nepredvidiv, dok u Putinovoj Rusiji, pravila su nepredvidiva, a rezultat fiksan..
        /// </summary>
        public static string KasparovCites {
            get {
                return ResourceManager.GetString("KasparovCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasparov se umirovio od šaha 2005. i posvetio se politici i promoviranju demokracije u Rusiji. 1996. postao je prvi svjetski prvak koji je izgubio od računala igrano na vremensku kontrolu ali je pobijedio u meču..
        /// </summary>
        public static string KasparovDescription {
            get {
                return ResourceManager.GetString("KasparovDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igrao je meč od 6 partija protiv računalnog programa Deep Fritz u Bonnu 2006. Meč je izgubio 4-2 sa 2 poraza i 4 remija. Za samo igranje u meču je primio 500,000 eura..
        /// </summary>
        public static string KramnikDescription {
            get {
                return ResourceManager.GetString("KramnikDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Često igram potez koji znam kako oboriti..
        /// </summary>
        public static string LarsenCites {
            get {
                return ResourceManager.GetString("LarsenCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kada vidiš dobar potez, potraži bolji.&lt;br/&gt;Dobar plan je jednako teško pronaći kao i njegovo dobro opravdanje..
        /// </summary>
        public static string LaskerCites {
            get {
                return ResourceManager.GetString("LaskerCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emanuel Lasker je držao titulu svjetskog prvaka 27 godina što je najduže u odnosu na ostale prvake. (1894.-1921.).
        /// </summary>
        public static string LaskerDescription {
            get {
                return ResourceManager.GetString("LaskerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauči igrati šah.
        /// </summary>
        public static string LearnToPlayChess {
            get {
                return ResourceManager.GetString("LearnToPlayChess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sve moje bitne informacije dostupne su na.
        /// </summary>
        public static string LinkedInContactDescription {
            get {
                return ResourceManager.GetString("LinkedInContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi se.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime ili lozinka su neispravno uneseni..
        /// </summary>
        public static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majstor.
        /// </summary>
        public static string Master {
            get {
                return ResourceManager.GetString("Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partije.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijednost minuta mora biti između 1 i 120..
        /// </summary>
        public static string MinutesRangeErrorMessage {
            get {
                return ResourceManager.GetString("MinutesRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti minute..
        /// </summary>
        public static string MinutesRequiredErrorMessage {
            get {
                return ResourceManager.GetString("MinutesRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomnogi svojim figurama tako da one mogu pomoći tebi..
        /// </summary>
        public static string MorphyCites {
            get {
                return ResourceManager.GetString("MorphyCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potezi.
        /// </summary>
        public static string Moves {
            get {
                return ResourceManager.GetString("Moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova igra.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova partija.
        /// </summary>
        public static string NewMatch {
            get {
                return ResourceManager.GetString("NewMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova lozinka.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinke si ne odgovaraju..
        /// </summary>
        public static string NewPasswordErrorMessage {
            get {
                return ResourceManager.GetString("NewPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi problem.
        /// </summary>
        public static string NewProblem {
            get {
                return ResourceManager.GetString("NewProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj pokušaja je: {0}.
        /// </summary>
        public static string NumberOfAttemptsMessage {
            get {
                return ResourceManager.GetString("NumberOfAttemptsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvaranja.
        /// </summary>
        public static string Openings {
            get {
                return ResourceManager.GetString("Openings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poredaj po.
        /// </summary>
        public static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinke si ne odgovaraju..
        /// </summary>
        public static string PasswordConfirmErrorMessage {
            get {
                return ResourceManager.GetString("PasswordConfirmErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka {0} mora biti barem {2} znakova duga..
        /// </summary>
        public static string PasswordErrorMessage {
            get {
                return ResourceManager.GetString("PasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednom prilikom je ponudio remi Svetozaru Gligoriću,
        ///            kojeg je on inicijalno odbio no predomislio se nakon par poteza i ponudio natrag remi. Petrosian ga nije čuo i nastavio igrati te na kraju pobijedio u partiji. Poslije se ispostavilo da je isključio slušni aparat i nije čuo Gligorića kad mu je nudio remi..
        /// </summary>
        public static string PetrosianDescription {
            get {
                return ResourceManager.GetString("PetrosianDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicije figura.
        /// </summary>
        public static string PiecePositions {
            get {
                return ResourceManager.GetString("PiecePositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mjesto.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igraj.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elo rating.
        /// </summary>
        public static string PlayingRating {
            get {
                return ResourceManager.GetString("PlayingRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemski rating.
        /// </summary>
        public static string ProblemRating {
            get {
                return ResourceManager.GetString("ProblemRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemi.
        /// </summary>
        public static string Problems {
            get {
                return ResourceManager.GetString("Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješnost.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string RatingFrom {
            get {
                return ResourceManager.GetString("RatingFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodovi moraju biti između 0 i 3500..
        /// </summary>
        public static string RatingFromRangeErrorMessage {
            get {
                return ResourceManager.GetString("RatingFromRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti minimalnu granicu rejting bodova..
        /// </summary>
        public static string RatingFromRequiredErrorMessage {
            get {
                return ResourceManager.GetString("RatingFromRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string RatingTo {
            get {
                return ResourceManager.GetString("RatingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodovi moraju biti između 0 i 3500..
        /// </summary>
        public static string RatingToRangeErrorMessage {
            get {
                return ResourceManager.GetString("RatingToRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti maksimalnu granicu rejting bodova..
        /// </summary>
        public static string RatingToRequiredErrorMessage {
            get {
                return ResourceManager.GetString("RatingToRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija dovršena.
        /// </summary>
        public static string RegistrationCompleted {
            get {
                return ResourceManager.GetString("RegistrationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste završili registracijski proces..
        /// </summary>
        public static string RegistrationCompletedMessage {
            get {
                return ResourceManager.GetString("RegistrationCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogreška u registraciji.
        /// </summary>
        public static string RegistrationError {
            get {
                return ResourceManager.GetString("RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogodila se pogreška tijekom primanja vašeg maila. Molimo vas pokušajte ponovno..
        /// </summary>
        public static string RegistrationErrorMessage {
            get {
                return ResourceManager.GetString("RegistrationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daljnje instrukcije za registraciju.
        /// </summary>
        public static string RegistrationInstructions {
            get {
                return ResourceManager.GetString("RegistrationInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za dovršetak registracijskog procesa provjerite email koji vam je poslan za daljnje instrukcije..
        /// </summary>
        public static string RegistrationInstructionsMessage {
            get {
                return ResourceManager.GetString("RegistrationInstructionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamti me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predaja.
        /// </summary>
        public static string Resign {
            get {
                return ResourceManager.GetString("Resign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezultat.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smyslov je bio bariton pa se kasnije okrenuo šahovskoj karijeri kada nije prošao  na audiciji u Bolshoi kazalištu..
        /// </summary>
        public static string SmyslovDescription {
            get {
                return ResourceManager.GetString("SmyslovDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rješenje.
        /// </summary>
        public static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riješi.
        /// </summary>
        public static string Solve {
            get {
                return ResourceManager.GetString("Solve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rješeno.
        /// </summary>
        public static string Solved {
            get {
                return ResourceManager.GetString("Solved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ispravno ste rješili problem, čestitamo..
        /// </summary>
        public static string SolvedProblemMessage {
            get {
                return ResourceManager.GetString("SolvedProblemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najčešće je bio opisivan kao univerzalan igrač. Nikada nije bio stručnjak za otvaranja. Specijalnost su mu bile središnjice, a bio je i veliki taktičar..
        /// </summary>
        public static string SpasskyDescription {
            get {
                return ResourceManager.GetString("SpasskyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početak.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šah nije za ljude slabog srca, on zahtijeva čitavu osobu. Za ulazak u srž ove igre čovjek mora postati šahovski rob. Šah je težak, zahtijeva puno rada ozbiljna razmišljanja i predana istraživanja..
        /// </summary>
        public static string SteinitzCites {
            get {
                return ResourceManager.GetString("SteinitzCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izjavio je 1877. da igra šah s bogom u snovima te da ga pobjeđuje s tim da mu daje  konja više na početku partije.
        ///            Steinitz je pobijedio Johannesa Zukertota 1886. i tako postao prvi
        ///            svjetski prvak..
        /// </summary>
        public static string SteinitzDescription {
            get {
                return ResourceManager.GetString("SteinitzDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Središnjice.
        /// </summary>
        public static string Strategies {
            get {
                return ResourceManager.GetString("Strategies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješnost.
        /// </summary>
        public static string SuccessRate {
            get {
                return ResourceManager.GetString("SuccessRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postoje dvije vrste žrtvi : korektne i moje.&lt;br/&gt;Igrati na remi sa bijelima na bilo koji način, je na nekom nivou zločin protiv šaha..
        /// </summary>
        public static string TalCites {
            get {
                return ResourceManager.GetString("TalCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postao svjetski prvak sa samo 23 godine..
        /// </summary>
        public static string TalDescription {
            get {
                return ResourceManager.GetString("TalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uvijek je bolje žrtovati protivnikove ljude..
        /// </summary>
        public static string TartakowerCites {
            get {
                return ResourceManager.GetString("TartakowerCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to puta.
        /// </summary>
        public static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepoznato.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bijeli.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bijeli igra?.
        /// </summary>
        public static string WhiteIsPlaying {
            get {
                return ResourceManager.GetString("WhiteIsPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bijeli je prvi na potezu.
        /// </summary>
        public static string WhiteIsPlayingFirst {
            get {
                return ResourceManager.GetString("WhiteIsPlayingFirst", resourceCulture);
            }
        }
    }
}
